I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    show morale blueh
Exception: Image 'morale' does not accept attributes 'blueh'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script
    show morale blueh
  File "C:\Program Files (x86)\renpy-8.3.3-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Program Files (x86)\renpy-8.3.3-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "C:\Program Files (x86)\renpy-8.3.3-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Program Files (x86)\renpy-8.3.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Program Files (x86)\renpy-8.3.3-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Program Files (x86)\renpy-8.3.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'morale' does not accept attributes 'blueh'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
MoraleLouLol 1.0
Wed Nov 20 19:07:48 2024
